### ISSUE TITLE
Charger les polices sans bloquer le rendu

### ISSUE THREAD

**Issue by MattiSG** [agile-france/site-2015#10]
La manière dont les polices sont chargées empêche tout affichage avant leur chargement. Peut-on éviter cela @fredZen ? Si Google Fonts le fait correctement, on peut abandonner l'idéal éthique  ;)

**Comment by MattiSG** [comment]
(ref : https://dev.opera.com/articles/better-font-face/ )

**Comment by fredZen** [comment]
Merci pour l'article, je viens d'apprendre quelque chose. Le fix parait
assez simple, je corriger ai sans doute samedi (pas besoin de sortir Google
:-)

Le jeu. 19 mars 2015 19:55, Matti Schneider notifications@github.com a
écrit :

**Comment by MattiSG** [comment]
Oui, l'article est super !  :)

Je ne serai pas dispo ce week-end, c'est pour ça que je blinde un peu now  ;)
