### ISSUE TITLE
Faire pointer 2015.conference-agile.fr vers la prod

### ISSUE THREAD

**Issue by MattiSG** [agile-france/site-2015#11]
Que ce soit github ou S3 (cf #9), @fredZen, peux-tu ajouter ce sous-domaine stp ?

**Comment by fredZen** [comment]
Oui, je prends

Le jeu. 19 mars 2015 20:29, Matti Schneider notifications@github.com a
écrit :

**Comment by fredZen** [comment]
Done (modulo le temps de propagation dns)

J'ai créé deux commandes gulp
- deploy_integ déploie sur gh-pages (https://agile-france.github.io/2015)
- deploy_prod déploie sur s3 http://2015.conference-agile.fr/) (ajourd'hui via travis, mais je me rends compte qu'il a 0 valeur ajoutée pour l'instant => à dégager à l'occas ?)

**Comment by fredZen** [comment]
En fait si, Travis est utile (c'est lui qui permet à tous les commiteurs de déployer en prod sans problèmes de distribution de clef)

La propagation DNS me semble OK ce matin
