### ISSUE TITLE
Texte qui dépasse

### ISSUE THREAD

**Issue by fredZen** [agile-france/site-2015#12]
Le texte entre la vidéo et la réservation (celui qui dit "mais pas seulement") est souvent trop gros par rapport à son background. C'est probablement dû au changement de police. @mattiSG je propose de réduire un poil l'ensemble des polices du site histoire de garder la cohérence d'ensemble.

**Comment by MattiSG** [comment]
J'avais observé ce comportement et mis un `background-repeat: repeat-y` pour limiter les dégâts, mais si tu vois un _sweet spot_ de taille de police go !  :)

**Comment by fredZen** [comment]
Après expérimentation, sur cette image là un simple background-size: 100% 100%; rend super bien je trouve

**Comment by MattiSG** [comment]
Parfait, go ! :)

**Comment by fredZen** [comment]
done

**Comment by MattiSG** [comment]
Merci !

in f8d01deebfd56a5d68d5f7389da07f8cb5e4dd54
