### ISSUE TITLE
Rajouter un pied-de-page avec les infos de contact du comité d’organisation

### ISSUE THREAD

**Issue by MattiSG** [agile-france/site-2015#14]

**Comment by fredZen** [comment]
Par exemple l'adresse mail contact@conference-agile.fr

**Comment by MattiSG** [comment]
@AnouchkaLabonne Pourrait-on avoir une enveloppe, par exemple ?

**Comment by AnouchkaLabonne** [comment]
Absolument :)

Je m’en occupe au plus vite. Si vous avez d’autres idées/suggestions, je prend.
