### ISSUE TITLE
Faire marcher le déploiement automatique

### ISSUE THREAD

**Issue by MattiSG** [agile-france/site-2015#16]
@fredZen Si je pousse sur `gulp`, Travis me dit ça :

```
Skipping a deployment with the s3 provider because this branch is not permitted
```

Penses-tu pouvoir régler le problème dans les 15 minutes qui viennent ? Sinon, on lance sans 9341d2969f999f2c66d89c1859d289e6eeac3932.

**Comment by fredZen** [comment]
Le gulp deploy_prod, c'est à toi de le lancer. Si tu veux je m'en charge
cette fois-ci, possible vers 9:30 je pense

Le mar. 24 mars 2015 09:10, Matti Schneider notifications@github.com a
écrit :

**Comment by MattiSG** [comment]
Ok, en fait `gulp deploy_prod` committe en local sur la branche `s3`, que je dois alors pousser pour que Travis déploie, c’est ça ? Pardon, je n’avais pas compris ce fonctionnement dans le détail.

Il en est à :

```
Cloning git@github.com:agile-france/2015.git into node_modules/gh-pages/.cache
```

**Comment by MattiSG** [comment]
Reste bloqué sur le clone. Kill + restart le fait bloquer sur fetching. Aucun trafic réseau.

Je veux bien que tu déploies pour cette fois-ci.

**Comment by fredZen** [comment]
Nonon, je confirme que de deploy_prod est aussi censé pousser. En tout cas c'est fait.

Serais bien partisan d'une solution plus simple, où la branche s3 contiendrait du source plutôt que du code minifié. Du coup, un déploiement en prod se réduirait à un git merge gulp s3, et le gulp build tournerait sous travis.

@alvinberthelot @MattiSG qu'en pensez-vous ? (mais peut-être plus simple au téléphone ?)

**Comment by MattiSG** [comment]
Oui, ce serait plus simple ainsi !

**Comment by alvinberthelot** [comment]
Salut,

Je reviens après la bataille.
Pour le déploiement, je vous laisse voir ça entre vous, je ne suis que "de passage".

Par contre je peux faire d'autres taches, avez vous des choses à traiter ?
Je vous proposerai bien de créer des taches via Gulp pour un développement confort (watcher, live-reload, ...). Qu'en pensez-vous ?

A ++

Alvin

**Comment by MattiSG** [comment]
Hello Alvin !

Aujourd'hui là tout de suite, on n'a pas vraiment besoin d'intervenir sur le site.
On aura certainement de petites interventions lors de l'ouverture du programme.

Le confort sera clairement apprécié à ce moment-là, mais pas d'urgence de mon côté  :)

**Comment by MattiSG** [comment]
Ça marche bien avec `gulp deploy_prod` :)
